### ISSUE TITLE
UV issue

### ISSUE THREAD

**Issue by Somshekardsi** [Javier-Garzo/Marching-cubes-on-Unity-3D#5] opened 2021-05-31 15:01 UTC
There seems to be an issue with UV. Sometimes texture gets stretched
![image](https://user-images.githubusercontent.com/66861200/120211730-e202bd00-c24e-11eb-8078-ed7edfd8409f.png)

**Comment by Javier-Garzo** [comment] 2021-05-31 18:02
It's already a known error. The texturization system have problems with the UV scales and the correct texture face orientation (also other UV problem). The problem is inside the BuildChunkJob.cs, line 75-95, where the UV calculation take place in the code. Now is a trivial method, it must use the marching cubes tables (static variables inside the bottom on the same script) .

**Comment by Somshekardsi** [comment] 2021-06-01 06:28
Okay, thank you.

**Comment by emre-sahinn** [comment] 2021-07-29 14:32
Are there any fix for this bug?

**Comment by Javier-Garzo** [comment] 2021-07-30 06:30
Yeah exists two possible solutions, you can see in this [stackexchange](https://gamedev.stackexchange.com/questions/53272/how-to-texture-a-surface-generated-by-marching-cubes-algorithm):

- The first solution of the post uses procedural generated textures, this change the texture of the terrain depending if it's undeground or superficial terrain. A video of Sebastian Lague with [this implementation](https://youtu.be/vTMEdHcKgM4?t=1250).
- The second solution of the post is the use a marching cube table for generating the texture. That's the idea for this project, however this post not talk about the interpolation (voxes that are smaller) that is another problem of the UV scales.

The current project texturization have problems with the UV directions and the UV scales (with interpolations active).
I try implementing the marching cube tables for the UV or fix the interpolation bug, but I fail. I must spend more hours trying a fix, but I little busy right now.

**Comment by emre-sahinn** [comment] 2021-08-18 08:14
Hi again, are there any updates? I tried implementing my self but no success..

**Comment by Javier-Garzo** [comment] 2021-08-19 06:18
I am working on that. Let's see if i can achieve something this week.

**Comment by emre-sahinn** [comment] 2021-08-26 20:54
> 
> 
> I am working on that. Let's see if i can achieve something this week.

Hi, did you succeed? I really need this update :')

**Comment by Javier-Garzo** [comment] 2021-08-27 08:36
Look to the new version, I improve the UV calculations removing the first image UV bug. Also create a little debug helper, you can active on runtime with F4 key.  
A image of both improvements (no interpolation terrain, bool inside MeshBuilderManager):
![Captura debug2](https://user-images.githubusercontent.com/58559223/131097175-48490c2d-c8d5-4f26-9b68-6f9a95d87fb0.PNG)

The brick texture still with a bad orientations and the interpolations have some UV problems (affected also by the illumination shader) : 
![Interpolation](https://user-images.githubusercontent.com/58559223/131098162-d88b51cc-8f63-46ad-8c74-7c9555d3aa0e.PNG)

However the visual results have improve a lot.

**Comment by emre-sahinn** [comment] 2021-08-29 12:17
Thanks a lot! you literally saved me, thanks for the update and awesome project

**Closed as completed** 2021-08-31 16:32 UTC
Labels: bug
